### ISSUE TITLE
Session config expire_on_close not matching Laravel default

### ISSUE THREAD

**Issue by bjuppa** [orchestral/testbench-core#8]
Is there a specific reason to have the `expire_on_close` config commented out in this package:
https://github.com/orchestral/testbench-core/blob/9b052bf9faacfd133f97493012e775ec435de54e/laravel/config/session.php#L34

...while in a [default Laravel app](https://github.com/laravel/laravel/blob/f4cba4f2b254456645036139129142df274a1ec1/config/session.php#L34) it defaults to `false`?

#### Background:
I found out when I set the session driver config to `file` in `getEnvironmentSetUp()` in one of my package tests, and got error "Undefined index: expire_on_close":

```php
$app['config']->set('session.driver', 'file');
```

The error went away after I explicitly set:

```php
$app['config']->set('session.expire_on_close', false);
```

**Comment by crynobone** [comment]
A test session shouldn't carry over between tests by default. So I decides to disable that by default. The default driver for session is array for testbench, not file. There are different that we tweak to make it more suitable for testing environment.

**Comment by bjuppa** [comment]
I agree, tests should not have session driver set to `file` by default, `array` is the way!

What I was wondering is why the other config `expire_on_close` is actively commented out instead of just kept as per Laravel's default session config file? Does it break anything having `expire_on_close` set?

My own case was actually when using using testbench-dusk where it'd make more sense to keep the session over a series of browser interactions, but let's not get distracted by that!

**Comment by bjuppa** [comment]
Haha, I see where you're going... but I must persist! 😄 

Regardless of the use case, I'm wondering if there's any specific reason why this core package actively removes a default config value?

**Comment by crynobone** [comment]
We starting building this package since Laravel 4, there were a time when this option isn't even available yet.

Furthermore initially this package doesn't even start the session but later on tweak to allow developer to assert session data. I don't want to tweak this now because it could cause a breaking change, even if I accept it this would go into 3.6, and if you want to test with multiple version of Laravel it would still be missing.

Testbench Dusk is still new and immature, it most suitable to define the defaults there.

**Comment by bjuppa** [comment]
I understand your reasons now, thank you!
